ui_env <- new.env(parent = globalenv())
sys.source(file.path("..", "..", "R", "domain_choices.R"), envir = ui_env)
sys.source(file.path("..", "..", "R", "app_ui.R"), envir = ui_env)

test_that("main app keeps configuration-only controls out of the UI", {
  ui_html <- paste(as.character(ui_env$be_app_ui()), collapse = "\n")

  expect_match(ui_html, "Export")
  expect_match(ui_html, "Logs")
  expect_match(ui_html, "live_log")
  expect_false(grepl("shared_root", ui_html, fixed = TRUE))
  expect_false(grepl("browse_shared_root", ui_html, fixed = TRUE))
  expect_false(grepl("save_shared_root", ui_html, fixed = TRUE))
  expect_false(grepl("subset_file", ui_html, fixed = TRUE))
  expect_false(grepl(">Status<", ui_html, fixed = TRUE))
  expect_false(grepl(">History<", ui_html, fixed = TRUE))
  expect_false(grepl(">Presets<", ui_html, fixed = TRUE))
  expect_false(grepl(">Shared Root<", ui_html, fixed = TRUE))
  expect_false(grepl("preset_detail", ui_html, fixed = TRUE))
})
